print("Bienvenido a la entrevista ")
print("Por favor, responda las siguientes preguntas:")
nombre = input("¿Cuál es su nombre? ")
edad = int(input("¿Cuál es su edad? "))
experiencia = input("¿Cuántos años de experiencia tiene en su campo? ")
habilidades = input("¿Cuáles son sus habilidades más destacadas? ")
disponibilidad = input("¿Está disponible para trabajar a tiempo completo? (Sí/No) ")
print("Gracias por sus respuestas, " + nombre + ". Aquí están las respuestas de su entrevista:")
print("Nombre:", nombre)                            
print("Edad:", edad)
print("Habilidades:", habilidades)
print("Disponibilidad para trabajar a tiempo completo:", disponibilidad)
print("¡Gracias por participar en la entrevista! Nos pondremos en contacto con usted pronto.")
print("¡Que tenga buen día!")